# Python Basic Tutorial 

print("Hola mundo")

B : new lines

DD : drop lines 

shift: select many lines

run : ctr + enter 

# Libraries

A library is a collection of modules or a single module. Modules are python programs that can be imported in another Python program. Libraries are the tools we will use to make our program.

Some special libraries such import $TensorFlow, Keras, Geopandas$ requiere of using Conda Promtp. We back this issue later. 


\begin{equation}
    u_i = \alpha
\end{equation}

In [3]:
# libraies t use date base and arrays
import pandas as pd
import numpy as np

np.DataFrame
sb.hexibn (c, y)

In [1]:
import pandas as pd


### Python Types

There are three key python types: int, float, string and boolean.

In [3]:
# Int type
a = 30

#print(type(a))
print(a)
type(a)

30


int

In [4]:
# Float type
a2 = 3.1416165516
print(type(a2))


<class 'float'>


In [6]:
#String type
c1 = "Machine Learning"
c2 = "Causal inference"
c3 = "2022-1"
type(c1)

c3

'2022-1'

In [3]:
g = 'g'

In [7]:
print(c1,'\n',c2)

#print(c1+" ; " +c2)

Machine Learning 
 Causal inference


In [11]:
c1[0:6]

'Machin'

In [12]:
print(c1[0], ";", c2[0:6])

M ; Causal


In [14]:
# get some strings 

#print(c1[0], ";", c2[0:6])

# Use f-string 

print(f'{c1} y {c2} course')

Machine Learning y Causal inference course


In [15]:
# Boolean variables
a = True  v
b = False  

print(type(a), '\n', type(b))



<class 'bool'> 
 <class 'bool'>


In [13]:
a = g

In [14]:
"a" == "b"


False

In [19]:
z1 = (10 < 20)

#z2 = (1==1)

#print(z2,'\n', z1)
int(z1)

1

## 3.0 Tuple

#### It is an ordered and immutable Python object

In [20]:
T1 = (1,4,8,10,20,15,4,5,8,8)

type(T1)


#print("Suma:", sum(T1),'\n', "Minimo:", min(T1), '\n', "Maximo:", max(T1))

tuple

In [25]:
T1[4]

20

In [28]:
T1[1:9] # let us for selecting from 0 to before 4 [0-3]

(4, 8, 10, 20, 15, 4, 5, 8)

In [30]:
T1[0:10] 

(1, 4, 8, 10, 20, 15, 4, 5, 8, 8)

In [42]:
# It is not possible to change
T1[1] = 5

TypeError: 'tuple' object does not support item assignment

# 4.0 List

#### It is an ordered and mutable Python container.

In [1]:
# Empty List

L1 = []

type(L1)

list

In [18]:
a = [3,4,5,"ATE", 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO']
type(a)
print(a)

a[0:2]

[3, 4, 5, 'ATE', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO']


[3, 4]

In [19]:
#a.append(["San Miguel", "La marina"])

a.append('San Borja')
print(a)

[3, 4, 5, 'ATE', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO', 'San Borja']


### Indexing
Selecting elements starting from 0. I know it sounds crazy. 
Selecting takes one position before the last requested column

In [20]:
print('first element:',a[0])
print(a[1:4]) # takes element position 1° to 3°, NOT 4°
print('first 5 element:',a[0:5]) # 0,1,2,3,4 

first element: 3
[4, 5, 'ATE']
first 5 element: [3, 4, 5, 'ATE', 'BARRANCO']


In [44]:
# use next line to complete list

b = ['ATE', 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO','CHACLACAYO','CHORRILLOS','CIENEGUILLA'
     ,'COMAS','EL_AGUSTINO','INDEPENDENCIA']

In [45]:
# last elements 
print(b[-1])

INDEPENDENCIA


In [46]:
print(b[-3:])

['COMAS', 'EL_AGUSTINO', 'INDEPENDENCIA']


In [48]:
len(b)

11

In [50]:
# add elements to list

num = [10,20,30]
b.extend(num)
print(b)
len(b)

['ATE', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO', 'CHACLACAYO', 'CHORRILLOS', 'CIENEGUILLA', 'COMAS', 'EL_AGUSTINO', 'INDEPENDENCIA', 10, 20, 30, 10, 20, 30]


17

# Dictionaries - THE WITCH
It is a unordered and mutable Python container.

In [51]:
# dictionary containing the population of the 5 largest german cities
population = {'Berlin': 3748148, 'Hamburg': 1822445, 'Munich': 1471508, 'Cologne': 1085664, 'Frankfurt': 753056 }
population.keys()


# enaho.rename( column, {var : ingreso_hora})

dict_keys(['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt'])

In [52]:
population['Cologne']

1085664

In [14]:
population['Hamburg']

1822445

In [24]:
population_18_19 = {'Berlin': [3748148, 38000, "alex"], 'Hamburg': [1822445, 1922445], 
                    'Munich': 1471508, 'Cologne': 1085664, 'Frankfurt': 753056 , 'lima': 1100000}

In [28]:
population_18_19['Berlin']

[3748148, 38000, 'alex']

In [17]:
pop_germnay = population_18_19["Berlin"][0] + population_18_19["Munich"] + population_18_19["Hamburg"][0]+ population_18_19["Frankfurt"]
pop_germnay

7795157

In [18]:
Postal_code =  {"LOMAS": {"UBIGEO": 40311, "Poverty Rate" : {"Upper_bound":"18.2%", "Lower_bound":"14.4%"}, "Population" : "20 mil"}}

Postal_code

{'LOMAS': {'UBIGEO': 40311,
  'Poverty Rate': {'Upper_bound': '18.2%', 'Lower_bound': '14.4%'},
  'Population': '20 mil'}}

In [19]:
Postal_code['LOMAS']['Poverty Rate']

{'Upper_bound': '18.2%', 'Lower_bound': '14.4%'}

In [20]:
Postal_code['LOMAS']['Poverty Rate']['Upper_bound']

'18.2%'

# Array (vectors and matrix)

### [Key Methods](https://cs231n.github.io/python-numpy-tutorial/)

| Method | Description |
| -------- | ------------ |
|dtype  | type of elements in the array|
|ndim   |  dimension of array|
|shape  |  tuple with the dimmension of the array|
|size |  total number of elements in the array|

In [56]:
a = np.array( [1, 2, 3, 4, 5] )
a
type(a)

numpy.ndarray

In [54]:
c1 = np.array([3,4,5,6,6])
c1

array([3, 4, 5, 6, 6])

In [61]:
print(a.size)
print(a.shape)
print(a.ndim)

len(a)

5
(5,)
1


5

In [69]:
# 2D array
M = np.array( [ [3, 4, 2], [1, 2, 6] ] )
print(M)

M1 = np.nan
M1
#print("n° elements:", M.size, '\n', "rows and columns:", M.shape, '\n', "n° dimension:", M.ndim)

[[3 4 2]
 [1 2 6]]


nan

### ***[Array Creation Routines](https://numpy.org/doc/stable/reference/routines.array-creation.html)***


|Function|Return|
| --- | --- |
|arange( )|array of sequence|
|eye( )|diagonal array|
|ones( )|array of ones|
|zeros( )|array of zeros|

In [30]:
import numpy as np

In [31]:
peru = np.arange(start = 1,stop = 13,step = 2)
print(peru)
type(peru)

[ 1  3  5  7  9 11]


numpy.ndarray

In [33]:
y = np.arange(1,11)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
y = np.arange( 0, 20, 5 )
print(y)
print(y[0:3])

[ 0  5 10 15]
[ 0  5 10]


In [26]:
y1 = np.arange( 1, 10 ) # one step 

In [75]:
a4 = np.ones(10)
print(a4, '\n')
a5 = np.ones((10,10))
print(a5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [28]:
a6 = np.zeros(5)
print(a6,'\n')
a7 = np.zeros((10,10))
print(a7)

[0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
a8 = np.array([np.arange(0,10), np.arange(10,20), np.arange(30,40), np.arange(-20,-10), np.arange(2,21,2)])
a8

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [30]:
a8[2:5,:]  # rows selecrtion

array([[ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [31]:
a8[:,0:6]  # columns selecrtion

array([[  0,   1,   2,   3,   4,   5],
       [ 10,  11,  12,  13,  14,  15],
       [ 30,  31,  32,  33,  34,  35],
       [-20, -19, -18, -17, -16, -15],
       [  2,   4,   6,   8,  10,  12]])

### ***[Array Manipulation](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)***

In [76]:
# Reshape

w = np.arange(0,24)
print( w )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [77]:
print(w.reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [78]:
print(w.reshape(24,1))

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [34]:
print(w.reshape(2,12))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [35]:
M1 = np.zeros( (8, 2) )
M2 = np.ones( (8, 4) )
print(M1,"\n","\n", M2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 
 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
M3 = np.hstack((M1,M2))  # add columns in horizontal way
M3

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

## Axis

### axis = 0 : vertical operation
### axis = 1 : horizontal operation

In [37]:
con1 = np.concatenate((M1,M2), axis = 1) # add more columns. This is a horizontal operation
con1

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

In [38]:
# Transpose
mat_3 = M3.T
print("mat5 \n" , mat_3)

mat5 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [39]:
M4 = np.array([[2,2,3,4,5,1],[1,5,5,9,8,2]])
print(M4)

[[2 2 3 4 5 1]
 [1 5 5 9 8 2]]


In [40]:
M5 = np.vstack((M3,M4))  # add columns in horizontal way
M5

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [2., 2., 3., 4., 5., 1.],
       [1., 5., 5., 9., 8., 2.]])

In [41]:
con2 = np.concatenate((M3,M4), axis = 0) # add more rows. This is a vertical operation
con2

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [2., 2., 3., 4., 5., 1.],
       [1., 5., 5., 9., 8., 2.]])

In [42]:

mat_5 = M5.T
print("mat4 \n" , mat_5)

mat4 
 [[0. 0. 0. 0. 0. 0. 0. 0. 2. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 2. 5.]
 [1. 1. 1. 1. 1. 1. 1. 1. 3. 5.]
 [1. 1. 1. 1. 1. 1. 1. 1. 4. 9.]
 [1. 1. 1. 1. 1. 1. 1. 1. 5. 8.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 2.]]


# [Pandas](https://pandas.pydata.org/docs/user_guide/index.html)
It helps us to store data in a 2-dimensional labeled data structure with columns of potentially different types.

In [37]:
# crear lists
students = ["Alejandro","Pedro","Ramiro","Axel","Juan"]
math = [15,16,10,12,13]
english = [13,9,16,14,17]
art = [12,16,15,19,10]

# Make a dictionary
grades = {"Students": students, "Math":math, "English":english, "Art":art}
grades

{'Students': ['Alejandro', 'Pedro', 'Ramiro', 'Axel', 'Juan'],
 'Math': [15, 16, 10, 12, 13],
 'English': [13, 9, 16, 14, 17],
 'Art': [12, 16, 15, 19, 10]}

In [38]:
data1 = pd.DataFrame(grades)
data1

Students  Math  English  Art
0  Alejandro    15       13   12
1      Pedro    16        9   16
2     Ramiro    10       16   15
3       Axel    12       14   19
4       Juan    13       17   10

In [39]:
# Change columns names
dic1 = { "Students":'St', "Math":'Ma', "English":'En', "Art":'Ar'} # dictionary
data1.rename( columns = dic1)

St  Ma  En  Ar
0  Alejandro  15  13  12
1      Pedro  16   9  16
2     Ramiro  10  16  15
3       Axel  12  14  19
4       Juan  13  17  10

In [40]:
data1.rename( columns = { "Students":'St', "Math":'Ma', "English":'En', "Art":'Ar'}  )

St  Ma  En  Ar
0  Alejandro  15  13  12
1      Pedro  16   9  16
2     Ramiro  10  16  15
3       Axel  12  14  19
4       Juan  13  17  10

In [41]:
# Add column and index row name
data = {'state': ['Lima', 'Piura', 'Tumbes', 'Cuzco', 'Ica', 'Puno'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [42]:
frame = pd.DataFrame(data, 
                      columns=["year", 'state', 'pop', 'debt'] ,
                      index=['one', 'two', 'three', 'four','five', 'six'] )

frame

year   state  pop debt
one    2000    Lima  1.5  NaN
two    2001   Piura  1.7  NaN
three  2002  Tumbes  3.6  NaN
four   2001   Cuzco  2.4  NaN
five   2002     Ica  2.9  NaN
six    2003    Puno  3.2  NaN

# Load  files : CSV, Excel

In [5]:
#using relative path
#import pandas as pd
#r'..\data\base1.xlsx'
base0 = pd.read_excel("C:/Users/PC/Documents/GitHub/14.38_Causal_ML/data/data2.xlsx")

print(type(base0))
base0.head()



<class 'pandas.core.frame.DataFrame'>


Latitude  Latitude2  Africa  Asia  Namer  Samer  Latitude:Latitude2  \
0    0.3111   0.096783       1     0      0      0            0.030109   
1    0.1367   0.018687       1     0      0      0            0.002554   
2    0.3778   0.142733       0     0      0      1            0.053924   
3    0.3000   0.090000       0     0      0      0            0.027000   
4    0.2683   0.071985       0     0      1      0            0.019314   

   Latitude:Africa  Latitude:Asia  Latitude:Namer  ...  Latitude2:Asia  \
0           0.3111            0.0          0.0000  ...             0.0   
1           0.1367            0.0          0.0000  ...             0.0   
2           0.0000            0.0          0.0000  ...             0.0   
3           0.0000            0.0          0.0000  ...             0.0   
4           0.0000            0.0          0.2683  ...             0.0   

   Latitude2:Namer  Latitude2:Samer  Africa:Asia  Africa:Namer  Africa:Samer  \
0         0.000000         0.000000            0             0             0   
1         0.000000         0.000000            0             0             0   
2         0.000000         0.142733            0             0             0   
3         0.000000         0.000000            0             0             0   
4         0.071985         0.000000            0             0             0   

   Asia:Namer  Asia:Samer  Namer:Samer  Exprop  
0           0           0            0    6.50  
1           0           0            0    5.36  
2           0           0            0    6.39  
3           0           0            0    9.32  
4           0           0            0    7.50  

[5 rows x 22 columns]

In [6]:
base0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Latitude            61 non-null     float64
 1   Latitude2           61 non-null     float64
 2   Africa              61 non-null     int64  
 3   Asia                61 non-null     int64  
 4   Namer               61 non-null     int64  
 5   Samer               61 non-null     int64  
 6   Latitude:Latitude2  61 non-null     float64
 7   Latitude:Africa     61 non-null     float64
 8   Latitude:Asia       61 non-null     float64
 9   Latitude:Namer      61 non-null     float64
 10  Latitude:Samer      61 non-null     float64
 11  Latitude2:Africa    61 non-null     float64
 12  Latitude2:Asia      61 non-null     float64
 13  Latitude2:Namer     61 non-null     float64
 14  Latitude2:Samer     61 non-null     float64
 15  Africa:Asia         61 non-null     int64  
 16  Africa:Nam

In [99]:
base1 = base1.rename( columns = { "wage":'salario', "Unnamed: 0":'id'}  )
base1

id    salario     lwage  sex  shs  hsg  scl  clg  ad  mw  ...  we  \
0        10   9.615385  2.263364    1    0    0    0    1   0   0  ...   0   
1        12  48.076923  3.872802    0    0    0    0    1   0   0  ...   0   
2        15  11.057692  2.403126    0    0    1    0    0   0   0  ...   0   
3        18  13.942308  2.634928    1    0    0    0    0   1   0  ...   0   
4        19  28.846154  3.361977    1    0    0    0    1   0   0  ...   0   
...     ...        ...       ...  ...  ...  ...  ...  ...  ..  ..  ...  ..   
5145  32620  14.769231  2.692546    0    0    0    0    1   0   0  ...   1   
5146  32624  23.076923  3.138833    1    0    0    1    0   0   0  ...   1   
5147  32626  38.461538  3.649659    0    0    0    0    0   1   0  ...   1   
5148  32631  32.967033  3.495508    0    0    1    0    0   0   0  ...   1   
5149  32643  17.307692  2.851151    0    0    0    0    0   1   0  ...   1   

      ne  exp1  exp2    exp3     exp4     occ  occ2     ind  ind2  
0      1   7.0  0.49   0.343   0.2401  3600.0    11  8370.0    18  
1      1  31.0  9.61  29.791  92.3521  3050.0    10  5070.0     9  
2      1  18.0  3.24   5.832  10.4976  6260.0    19   770.0     4  
3      1  25.0  6.25  15.625  39.0625   420.0     1  6990.0    12  
4      1  22.0  4.84  10.648  23.4256  2015.0     6  9470.0    22  
...   ..   ...   ...     ...      ...     ...   ...     ...   ...  
5145   0   9.0  0.81   0.729   0.6561  4700.0    16  4970.0     9  
5146   0  12.0  1.44   1.728   2.0736  4110.0    13  8680.0    20  
5147   0  11.0  1.21   1.331   1.4641  1550.0     4  3680.0     6  
5148   0  10.0  1.00   1.000   1.0000  2920.0     9  6570.0    11  
5149   0  14.0  1.96   2.744   3.8416  1610.0     5  7460.0    14  

[5150 rows x 21 columns]

In [101]:
base1 = base1.drop(["id","ind2"], axis=1)




# axis 1 : horizontal operation

# axis 0 : vertical operation

KeyError: "['id' 'ind2'] not found in axis"

In [102]:
base1

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0      9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
1     48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2     11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3     13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4     28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
...         ...       ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..   ...   
5145  14.769231  2.692546    0    0    0    0    1   0   0   0   1   0   9.0   
5146  23.076923  3.138833    1    0    0    1    0   0   0   0   1   0  12.0   
5147  38.461538  3.649659    0    0    0    0    0   1   0   0   1   0  11.0   
5148  32.967033  3.495508    0    0    1    0    0   0   0   0   1   0  10.0   
5149  17.307692  2.851151    0    0    0    0    0   1   0   0   1   0  14.0   

      exp2    exp3     exp4     occ  occ2     ind  
0     0.49   0.343   0.2401  3600.0    11  8370.0  
1     9.61  29.791  92.3521  3050.0    10  5070.0  
2     3.24   5.832  10.4976  6260.0    19   770.0  
3     6.25  15.625  39.0625   420.0     1  6990.0  
4     4.84  10.648  23.4256  2015.0     6  9470.0  
...    ...     ...      ...     ...   ...     ...  
5145  0.81   0.729   0.6561  4700.0    16  4970.0  
5146  1.44   1.728   2.0736  4110.0    13  8680.0  
5147  1.21   1.331   1.4641  1550.0     4  3680.0  
5148  1.00   1.000   1.0000  2920.0     9  6570.0  
5149  1.96   2.744   3.8416  1610.0     5  7460.0  

[5150 rows x 19 columns]

In [103]:
base1.drop([1,3], axis = 0)

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0      9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
2     11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
4     28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
5     11.730769  2.462215    1    0    0    0    1   0   0   0   0   1   1.0   
6     19.230769  2.956512    1    0    1    0    0   0   0   0   0   1  42.0   
...         ...       ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..   ...   
5145  14.769231  2.692546    0    0    0    0    1   0   0   0   1   0   9.0   
5146  23.076923  3.138833    1    0    0    1    0   0   0   0   1   0  12.0   
5147  38.461538  3.649659    0    0    0    0    0   1   0   0   1   0  11.0   
5148  32.967033  3.495508    0    0    1    0    0   0   0   0   1   0  10.0   
5149  17.307692  2.851151    0    0    0    0    0   1   0   0   1   0  14.0   

       exp2    exp3      exp4     occ  occ2     ind  
0      0.49   0.343    0.2401  3600.0    11  8370.0  
2      3.24   5.832   10.4976  6260.0    19   770.0  
4      4.84  10.648   23.4256  2015.0     6  9470.0  
5      0.01   0.001    0.0001  1650.0     5  7460.0  
6     17.64  74.088  311.1696  5120.0    17  7280.0  
...     ...     ...       ...     ...   ...     ...  
5145   0.81   0.729    0.6561  4700.0    16  4970.0  
5146   1.44   1.728    2.0736  4110.0    13  8680.0  
5147   1.21   1.331    1.4641  1550.0     4  3680.0  
5148   1.00   1.000    1.0000  2920.0     9  6570.0  
5149   1.96   2.744    3.8416  1610.0     5  7460.0  

[5148 rows x 19 columns]

## Slicing  dataframe 

In [105]:
#select rows using positions

base1.iloc[0:6]

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0   9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
1  48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2  11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3  13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4  28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
5  11.730769  2.462215    1    0    0    0    1   0   0   0   0   1   1.0   

   exp2    exp3     exp4     occ  occ2     ind  
0  0.49   0.343   0.2401  3600.0    11  8370.0  
1  9.61  29.791  92.3521  3050.0    10  5070.0  
2  3.24   5.832  10.4976  6260.0    19   770.0  
3  6.25  15.625  39.0625   420.0     1  6990.0  
4  4.84  10.648  23.4256  2015.0     6  9470.0  
5  0.01   0.001   0.0001  1650.0     5  7460.0

In [106]:
# select columns using positions

base1.iloc[:,0:5]

salario     lwage  sex  shs  hsg
0      9.615385  2.263364    1    0    0
1     48.076923  3.872802    0    0    0
2     11.057692  2.403126    0    0    1
3     13.942308  2.634928    1    0    0
4     28.846154  3.361977    1    0    0
...         ...       ...  ...  ...  ...
5145  14.769231  2.692546    0    0    0
5146  23.076923  3.138833    1    0    0
5147  38.461538  3.649659    0    0    0
5148  32.967033  3.495508    0    0    1
5149  17.307692  2.851151    0    0    0

[5150 rows x 5 columns]

In [109]:
# row index and columns names 

base1.loc[:,['salario', 'lwage']]

salario     lwage
0      9.615385  2.263364
1     48.076923  3.872802
2     11.057692  2.403126
3     13.942308  2.634928
4     28.846154  3.361977
...         ...       ...
5145  14.769231  2.692546
5146  23.076923  3.138833
5147  38.461538  3.649659
5148  32.967033  3.495508
5149  17.307692  2.851151

[5150 rows x 2 columns]

In [119]:
base3 = base1[['lwage','salario']]

In [120]:
base3

lwage    salario
0     2.263364   9.615385
1     3.872802  48.076923
2     2.403126  11.057692
3     2.634928  13.942308
4     3.361977  28.846154
...        ...        ...
5145  2.692546  14.769231
5146  3.138833  23.076923
5147  3.649659  38.461538
5148  3.495508  32.967033
5149  2.851151  17.307692

[5150 rows x 2 columns]

In [140]:
frame.loc[['one','two']]

year  state  pop debt
one  2000   Lima  1.5    1
two  2001  Piura  1.7  NaN

In [121]:
base1[base1['sex']==1]

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0      9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
3     13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4     28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
5     11.730769  2.462215    1    0    0    0    1   0   0   0   0   1   1.0   
6     19.230769  2.956512    1    0    1    0    0   0   0   0   0   1  42.0   
...         ...       ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..   ...   
5137  13.461538  2.599837    1    0    1    0    0   0   0   0   1   0   8.0   
5138  19.711538  2.981204    1    0    0    0    0   1   0   0   1   0   8.0   
5140  45.546559  3.818735    1    0    0    0    1   0   0   0   1   0   5.0   
5143  24.038462  3.179655    1    0    0    0    1   0   0   0   1   0  17.0   
5146  23.076923  3.138833    1    0    0    1    0   0   0   0   1   0  12.0   

       exp2    exp3      exp4     occ  occ2     ind  
0      0.49   0.343    0.2401  3600.0    11  8370.0  
3      6.25  15.625   39.0625   420.0     1  6990.0  
4      4.84  10.648   23.4256  2015.0     6  9470.0  
5      0.01   0.001    0.0001  1650.0     5  7460.0  
6     17.64  74.088  311.1696  5120.0    17  7280.0  
...     ...     ...       ...     ...   ...     ...  
5137   0.64   0.512    0.4096  4720.0    16  8590.0  
5138   0.64   0.512    0.4096  2000.0     6  8090.0  
5140   0.25   0.125    0.0625  3255.0    10  8190.0  
5143   2.89   4.913    8.3521  2550.0     8  9480.0  
5146   1.44   1.728    2.0736  4110.0    13  8680.0  

[2289 rows x 19 columns]

In [122]:
base1[base1.exp1 > 10].head(10)

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
1   48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2   11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3   13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4   28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
6   19.230769  2.956512    1    0    1    0    0   0   0   0   0   1  42.0   
7   19.230769  2.956512    0    0    1    0    0   0   0   0   0   1  37.0   
8   12.000000  2.484907    1    0    1    0    0   0   0   0   0   1  31.0   
11  12.019231  2.486508    0    0    1    0    0   0   0   0   0   1  30.0   
13  13.461538  2.599837    1    0    0    1    0   0   0   0   0   1  20.5   
14  16.346154  2.793993    1    0    0    0    1   0   0   0   0   1  25.0   

       exp2       exp3        exp4     occ  occ2     ind  
1    9.6100  29.791000   92.352100  3050.0    10  5070.0  
2    3.2400   5.832000   10.497600  6260.0    19   770.0  
3    6.2500  15.625000   39.062500   420.0     1  6990.0  
4    4.8400  10.648000   23.425600  2015.0     6  9470.0  
6   17.6400  74.088000  311.169600  5120.0    17  7280.0  
7   13.6900  50.653000  187.416100  5240.0    17  5680.0  
8    9.6100  29.791000   92.352100  4040.0    13  8590.0  
11   9.0000  27.000000   81.000000  4220.0    14  8270.0  
13   4.2025   8.615125   17.661006  3645.0    11  8190.0  
14   6.2500  15.625000   39.062500   110.0     1  7870.0

In [124]:
base1[base1.exp1 < 5]

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
5     11.730769  2.462215    1    0    0    0    1   0   0   0   0   1   1.0   
9     19.230769  2.956512    1    0    0    0    1   0   0   0   0   1   4.0   
17     8.653846  2.158004    0    0    0    1    0   0   0   0   0   1   3.5   
27    12.000000  2.484907    0    0    0    1    0   0   0   0   0   1   4.5   
30    42.307692  3.744969    1    0    0    0    0   1   0   0   0   1   0.0   
...         ...       ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..   ...   
5110  15.865385  2.764140    1    0    0    0    0   1   0   0   1   0   0.0   
5114  18.750000  2.931194    1    0    0    0    1   0   0   0   1   0   2.0   
5115  20.913462  3.040393    1    0    0    1    0   0   0   0   1   0   4.5   
5118  12.019231  2.486508    0    0    0    1    0   0   0   0   1   0   4.0   
5121  15.865385  2.764140    0    0    0    0    0   1   0   0   1   0   2.0   

        exp2      exp3      exp4     occ  occ2     ind  
5     0.0100  0.001000  0.000100  1650.0     5  7460.0  
9     0.1600  0.064000  0.025600  3255.0    10  8190.0  
17    0.1225  0.042875  0.015006  7410.0    20   570.0  
27    0.2025  0.091125  0.041006  6330.0    19   770.0  
30    0.0000  0.000000  0.000000  4700.0    16  4795.0  
...      ...       ...       ...     ...   ...     ...  
5110  0.0000  0.000000  0.000000  3230.0    10  8180.0  
5114  0.0400  0.008000  0.001600  2000.0     6  8370.0  
5115  0.2025  0.091125  0.041006  4600.0    15  8470.0  
5118  0.1600  0.064000  0.025600  9620.0    22  6170.0  
5121  0.0400  0.008000  0.001600  2200.0     8  7870.0  

[1058 rows x 19 columns]

In [154]:
base1[(base1['sex']==1) & (base1.exp1 > 10) ].head(10)
base1[(base1['sex']==1) | (base1.exp1 > 10) ].head(10)

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0   9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
1  48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2  11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3  13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4  28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
5  11.730769  2.462215    1    0    0    0    1   0   0   0   0   1   1.0   
6  19.230769  2.956512    1    0    1    0    0   0   0   0   0   1  42.0   
7  19.230769  2.956512    0    0    1    0    0   0   0   0   0   1  37.0   
8  12.000000  2.484907    1    0    1    0    0   0   0   0   0   1  31.0   
9  19.230769  2.956512    1    0    0    0    1   0   0   0   0   1   4.0   

    exp2    exp3      exp4     occ  occ2     ind  
0   0.49   0.343    0.2401  3600.0    11  8370.0  
1   9.61  29.791   92.3521  3050.0    10  5070.0  
2   3.24   5.832   10.4976  6260.0    19   770.0  
3   6.25  15.625   39.0625   420.0     1  6990.0  
4   4.84  10.648   23.4256  2015.0     6  9470.0  
5   0.01   0.001    0.0001  1650.0     5  7460.0  
6  17.64  74.088  311.1696  5120.0    17  7280.0  
7  13.69  50.653  187.4161  5240.0    17  5680.0  
8   9.61  29.791   92.3521  4040.0    13  8590.0  
9   0.16   0.064    0.0256  3255.0    10  8190.0

In [159]:
base1.sort_values(["exp1","salario"]).head(20)
base1['dummy'] = np.nan # nan values
base1 

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0      9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
1     48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2     11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3     13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4     28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
...         ...       ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..   ...   
5145  14.769231  2.692546    0    0    0    0    1   0   0   0   1   0   9.0   
5146  23.076923  3.138833    1    0    0    1    0   0   0   0   1   0  12.0   
5147  38.461538  3.649659    0    0    0    0    0   1   0   0   1   0  11.0   
5148  32.967033  3.495508    0    0    1    0    0   0   0   0   1   0  10.0   
5149  17.307692  2.851151    0    0    0    0    0   1   0   0   1   0  14.0   

      exp2    exp3     exp4     occ  occ2     ind  dummy  
0     0.49   0.343   0.2401  3600.0    11  8370.0    NaN  
1     9.61  29.791  92.3521  3050.0    10  5070.0    NaN  
2     3.24   5.832  10.4976  6260.0    19   770.0    NaN  
3     6.25  15.625  39.0625   420.0     1  6990.0    NaN  
4     4.84  10.648  23.4256  2015.0     6  9470.0    NaN  
...    ...     ...      ...     ...   ...     ...    ...  
5145  0.81   0.729   0.6561  4700.0    16  4970.0    NaN  
5146  1.44   1.728   2.0736  4110.0    13  8680.0    NaN  
5147  1.21   1.331   1.4641  1550.0     4  3680.0    NaN  
5148  1.00   1.000   1.0000  2920.0     9  6570.0    NaN  
5149  1.96   2.744   3.8416  1610.0     5  7460.0    NaN  

[5150 rows x 20 columns]

In [166]:
base1.loc[base1['exp1'] > 10, "dummy"] = 1
base1

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0      9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
1     48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2     11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3     13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4     28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
...         ...       ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..   ...   
5145  14.769231  2.692546    0    0    0    0    1   0   0   0   1   0   9.0   
5146  23.076923  3.138833    1    0    0    1    0   0   0   0   1   0  12.0   
5147  38.461538  3.649659    0    0    0    0    0   1   0   0   1   0  11.0   
5148  32.967033  3.495508    0    0    1    0    0   0   0   0   1   0  10.0   
5149  17.307692  2.851151    0    0    0    0    0   1   0   0   1   0  14.0   

      exp2    exp3     exp4     occ  occ2     ind  dummy  
0     0.49   0.343   0.2401  3600.0    11  8370.0    NaN  
1     9.61  29.791  92.3521  3050.0    10  5070.0    1.0  
2     3.24   5.832  10.4976  6260.0    19   770.0    1.0  
3     6.25  15.625  39.0625   420.0     1  6990.0    1.0  
4     4.84  10.648  23.4256  2015.0     6  9470.0    1.0  
...    ...     ...      ...     ...   ...     ...    ...  
5145  0.81   0.729   0.6561  4700.0    16  4970.0    NaN  
5146  1.44   1.728   2.0736  4110.0    13  8680.0    1.0  
5147  1.21   1.331   1.4641  1550.0     4  3680.0    1.0  
5148  1.00   1.000   1.0000  2920.0     9  6570.0    NaN  
5149  1.96   2.744   3.8416  1610.0     5  7460.0    1.0  

[5150 rows x 20 columns]

# If condition

Function **if** test conditions. 
- Equals: a == b
- Not Equals: a != b
- Less than: a < b
- Less than or equal to: a <= b
- Greater than: a > b
- Greater than or equal to: a >= b

<img src="https://www.dropbox.com/s/8xwqk2ze1116qvp/if-statement.jpg?dl=1" alt="image info" />

In [170]:
A = 20
B = 30

if A == B:
    print( 'Test expresion 1 is True' )
    
elif A > B:
    print( 'Test expresion 2 is True' )

elif A >= B:
    print( 'Test expresion 3 is True' )
    
elif A < B:
    print( 'Test expresion 4 is True' )
    
elif A <= B:
    print( 'Test expresion 5 is True' )
    
else:
    print( 'Test expresion 6 is True' )

Test expresion 4 is True


# For Loops

A for loop is used for iterating over a sequence. It has the following structure:

<img src="https://www.dropbox.com/s/a51fbr4m0vpvobe/for_loop.jpg?dl=1" alt="image info" />



In [127]:
secuencia = np.arange(1,20)
secuencia

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [49]:
secuencia = np.arange(1,20)

for i in secuencia:
    print("numero",i)
    

numero 1
numero 2
numero 3
numero 4
numero 5
numero 6
numero 7
numero 8
numero 9
numero 10
numero 11
numero 12
numero 13
numero 14
numero 15
numero 16
numero 17
numero 18
numero 19


In [229]:
born = [ 1980 , 1990 , 2010 , 2008 , 2005, 1999]
years = [2023 , 2021 , 2022 , 2026 , 2027, 2028 ]
age_finish = []

print(len(age),'\n')

for i in np.arange(0,len(age)):
        new = years[ i ] - born[ i ] 
        age_finish.append( new )

age_finish

5 



[43, 31, 12, 18, 22]

In [177]:
# secuencia
students = [ 'Miguel' , 'Anthony', 'Paul', 'Rodrigo', 'Jason' ]

# age
gr_age = [ 20, 18, 15, 20, 22]

semester = [ "2018-1", "2018-2", "2019-1", "2019-2","2020-1"]

# Loops
for student, age, sem in zip( students , gr_age , semester):
    print(f'{ student } is { age }, semester {sem}')

Miguel is 20, semester 2018-1
Anthony is 18, semester 2018-2
Paul is 15, semester 2019-1
Rodrigo is 20, semester 2019-2
Jason is 22, semester 2020-1


# Nested For Loop

In [178]:
age_class = [ [11, 12, 11] , [15, 16, 16] , [17, 17, 18]]

for classs in age_class:
    print( classs )
    
    for age in classs:
        print( age )

[11, 12, 11]
11
12
11
[15, 16, 16]
15
16
16
[17, 17, 18]
17
17
18


# Functions

- `Arguments` − Elements that the function will use to make operations. Arguments are optional and can have default values.

- `Function Body` − This defines what your function does.
- `return` − Specifies the variable that will be the output of the function.

Return Value − The return value of a function is the last expression in the function body to be evaluated.
<br><br>
<font size="4">
<font color='green'>def</font> function_name <font color='green'>(arg_1, arg_2, ...) </font>:<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Function body <br>
    <br> &nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>return</font> result<br>
</font>

In [50]:
def suma(x, y):
    mate = (x + y)*15
    return mate

In [51]:
suma(10,4)

210